export const siteConfig = {
  name: "PhotoReady Home Prep",
  title: "PhotoReady Home Prep | Pre-Listing Home Prep in Harrisburg, PA",
  description:
    "PhotoReady helps Harrisburg and Central PA homeowners and real estate agents prepare homes for listing with cleanouts, painting, flooring, cleaning, repairs, and curb appeal services.",
  url: "https://photoreadyhomeprep.com",
  phone: "(717) 317-2862",
  phoneHref: "tel:+17173172862",
  email: "hello@photoreadyhomeprep.com",
  address: {
    city: "Harrisburg",
    state: "PA",
    region: "Central Pennsylvania",
  },
  keywords: [
    "pre-listing home prep Harrisburg PA",
    "home prep before selling",
    "real estate listing prep",
    "prepare house for sale Central PA",
    "cleanouts before listing",
    "painting before selling a house",
    "move-out cleaning before listing",
    "flooring before listing",
    "curb appeal before selling",
    "real estate agent vendor Harrisburg PA",
    "home prep Mechanicsburg PA",
    "home prep Camp Hill PA",
    "home prep Carlisle PA",
    "Cumberland County home prep",
    "Dauphin County pre-listing services",
  ],
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "For Agents", href: "/for-agents" },
    { label: "How It Works", href: "/how-it-works" },
    { label: "Contact", href: "/contact" },
  ],
};
